import { createEmptyGrid_ } from "./sudokuGenerator.js";

export let arrayTemplates = Array(7).fill(null).map(createEmptyGrid_);

arrayTemplates[0] = [[
    {value: null, figure: 1,},
    {value: null, figure: 1,},
    {value: null, figure: 1,},
    {value: null, figure: 1,},
    {value: null, figure: 2,},
    {value: null, figure: 2,},
    {value: null, figure: 2,},
    {value: null, figure: 2,},
    {value: null, figure: 3,}
],
    [
        {value: null, figure: 1,},
        {value: null, figure: 4,},
        {value: null, figure: 1,},
        {value: null, figure: 2,},
        {value: null, figure: 2,},
        {value: null, figure: 3,},
        {value: null, figure: 3,},
        {value: null, figure: 3,},
        {value: null, figure: 3,}
    ],
    [
        {value: null, figure: 1,},
        {value: null, figure: 4,},
        {value: null, figure: 1,},
        {value: null, figure: 2,},
        {value: null, figure: 2,},
        {value: null, figure: 3,},
        {value: null, figure: 3,},
        {value: null, figure: 5,},
        {value: null, figure: 3,}],
    [
        {value: null, figure: 4,},
        {value: null, figure: 4,},
        {value: null, figure: 1,},
        {value: null, figure: 2,},
        {value: null, figure: 6,},
        {value: null, figure: 3,},
        {value: null, figure: 5,},
        {value: null, figure: 5,},
        {value: null, figure: 5,}],
    [
        {value: null, figure: 4,},
        {value: null, figure: 6,},
        {value: null, figure: 6,},
        {value: null, figure: 6,},
        {value: null, figure: 6,},
        {value: null, figure: 6,},
        {value: null, figure: 6,},
        {value: null, figure: 6,},
        {value: null, figure: 5,}],
    [
        {value: null, figure: 4,},
        {value: null, figure: 4,},
        {value: null, figure: 4,},
        {value: null, figure: 7,},
        {value: null, figure: 6,},
        {value: null, figure: 8,},
        {value: null, figure: 9,},
        {value: null, figure: 5,},
        {value: null, figure: 5,}],
    [
        {value: null, figure: 7,},
        {value: null, figure: 4,},
        {value: null, figure: 7,},
        {value: null, figure: 7,},
        {value: null, figure: 8,},
        {value: null, figure: 8,},
        {value: null, figure: 9,},
        {value: null, figure: 5,},
        {value: null, figure: 9,}],
    [
        {value: null, figure: 7,},
        {value: null, figure: 7,},
        {value: null, figure: 7,},
        {value: null, figure: 7,},
        {value: null, figure: 8,},
        {value: null, figure: 8,},
        {value: null, figure: 9,},
        {value: null, figure: 5,},
        {value: null, figure: 9,}],
    [
        {value: null, figure: 7,},
        {value: null, figure: 8,},
        {value: null, figure: 8,},
        {value: null, figure: 8,},
        {value: null, figure: 8,},
        {value: null, figure: 9,},
        {value: null, figure: 9,},
        {value: null, figure: 9,},
        {value: null, figure: 9,},
    ]
];
arrayTemplates[1] = [[
    {value: null, figure: 1,},
    {value: null, figure: 2,},
    {value: null, figure: 2,},
    {value: null, figure: 2,},
    {value: null, figure: 2,},
    {value: null, figure: 3,},
    {value: null, figure: 3,},
    {value: null, figure: 3,},
    {value: null, figure: 4,}
    ],
    [
        {value: null, figure: 1,},
        {value: null, figure: 1,},
        {value: null, figure: 1,},
        {value: null, figure: 2,},
        {value: null, figure: 3,},
        {value: null, figure: 3,},
        {value: null, figure: 3,},
        {value: null, figure: 3,},
        {value: null, figure: 4,}
    ],
    [
        {value: null, figure: 1,},
        {value: null, figure: 1,},
        {value: null, figure: 2,},
        {value: null, figure: 2,},
        {value: null, figure: 5,},
        {value: null, figure: 3,},
        {value: null, figure: 4,},
        {value: null, figure: 3,},
        {value: null, figure: 4,}],
    [
        {value: null, figure: 1,},
        {value: null, figure: 2,},
        {value: null, figure: 2,},
        {value: null, figure: 5,},
        {value: null, figure: 5,},
        {value: null, figure: 5,},
        {value: null, figure: 4,},
        {value: null, figure: 4,},
        {value: null, figure: 4,}],
    [
        {value: null, figure: 1,},
        {value: null, figure: 1,},
        {value: null, figure: 6,},
        {value: null, figure: 6,},
        {value: null, figure: 5,},
        {value: null, figure: 4,},
        {value: null, figure: 4,},
        {value: null, figure: 9,},
        {value: null, figure: 9,}],
    [
        {value: null, figure: 6,},
        {value: null, figure: 6,},
        {value: null, figure: 6,},
        {value: null, figure: 5,},
        {value: null, figure: 5,},
        {value: null, figure: 5,},
        {value: null, figure: 7,},
        {value: null, figure: 7,},
        {value: null, figure: 9,}],
    [
        {value: null, figure: 6,},
        {value: null, figure: 8,},
        {value: null, figure: 6,},
        {value: null, figure: 8,},
        {value: null, figure: 5,},
        {value: null, figure: 7,},
        {value: null, figure: 7,},
        {value: null, figure: 9,},
        {value: null, figure: 9,}],
    [
        {value: null, figure: 6,},
        {value: null, figure: 8,},
        {value: null, figure: 8,},
        {value: null, figure: 8,},
        {value: null, figure: 8,},
        {value: null, figure: 7,},
        {value: null, figure: 9,},
        {value: null, figure: 9,},
        {value: null, figure: 9,}
    ],
    [
        {value: null, figure: 6,},
        {value: null, figure: 8,},
        {value: null, figure: 8,},
        {value: null, figure: 8,},
        {value: null, figure: 7,},
        {value: null, figure: 7,},
        {value: null, figure: 7,},
        {value: null, figure: 7,},
        {value: null, figure: 9,},
    ]
]

arrayTemplates[2] = [[
    {value: null, figure: 1,},
    {value: null, figure: 1,},
    {value: null, figure: 1,},
    {value: null, figure: 1,},
    {value: null, figure: 2,},
    {value: null, figure: 2,},
    {value: null, figure: 3,},
    {value: null, figure: 3,},
    {value: null, figure: 3,}
],
    [
        {value: null, figure: 1,},
        {value: null, figure: 1,},
        {value: null, figure: 2,},
        {value: null, figure: 2,},
        {value: null, figure: 2,},
        {value: null, figure: 2,},
        {value: null, figure: 3,},
        {value: null, figure: 3,},
        {value: null, figure: 3,}
    ],
    [
        {value: null, figure: 1,},
        {value: null, figure: 4,},
        {value: null, figure: 4,},
        {value: null, figure: 5,},
        {value: null, figure: 2,},
        {value: null, figure: 2,},
        {value: null, figure: 3,},
        {value: null, figure: 6,},
        {value: null, figure: 3,}],
    [
        {value: null, figure: 1,},
        {value: null, figure: 1,},
        {value: null, figure: 4,},
        {value: null, figure: 5,},
        {value: null, figure: 2,},
        {value: null, figure: 5,},
        {value: null, figure: 3,},
        {value: null, figure: 6,},
        {value: null, figure: 6,}],
    [
        {value: null, figure: 4,},
        {value: null, figure: 4,},
        {value: null, figure: 4,},
        {value: null, figure: 5,},
        {value: null, figure: 5,},
        {value: null, figure: 5,},
        {value: null, figure: 6,},
        {value: null, figure: 6,},
        {value: null, figure: 6,}],
    [
        {value: null, figure: 7,},
        {value: null, figure: 7,},
        {value: null, figure: 4,},
        {value: null, figure: 5,},
        {value: null, figure: 8,},
        {value: null, figure: 5,},
        {value: null, figure: 9,},
        {value: null, figure: 6,},
        {value: null, figure: 6,}],
    [
        {value: null, figure: 7,},
        {value: null, figure: 4,},
        {value: null, figure: 4,},
        {value: null, figure: 5,},
        {value: null, figure: 8,},
        {value: null, figure: 8,},
        {value: null, figure: 9,},
        {value: null, figure: 6,},
        {value: null, figure: 9,}],
    [
        {value: null, figure: 7,},
        {value: null, figure: 7,},
        {value: null, figure: 8,},
        {value: null, figure: 8,},
        {value: null, figure: 8,},
        {value: null, figure: 8,},
        {value: null, figure: 9,},
        {value: null, figure: 9,},
        {value: null, figure: 9,}
    ],
    [
        {value: null, figure: 7,},
        {value: null, figure: 7,},
        {value: null, figure: 7,},
        {value: null, figure: 7,},
        {value: null, figure: 8,},
        {value: null, figure: 8,},
        {value: null, figure: 9,},
        {value: null, figure: 9,},
        {value: null, figure: 9,},
    ]
]

arrayTemplates[3] = [[
    {value: null, figure: 1,},
    {value: null, figure: 1,},
    {value: null, figure: 1,},
    {value: null, figure: 1,},
    {value: null, figure: 2,},
    {value: null, figure: 2,},
    {value: null, figure: 2,},
    {value: null, figure: 3,},
    {value: null, figure: 3,}
],
    [
        {value: null, figure: 4,},
        {value: null, figure: 1,},
        {value: null, figure: 4,},
        {value: null, figure: 1,},
        {value: null, figure: 2,},
        {value: null, figure: 2,},
        {value: null, figure: 2,},
        {value: null, figure: 2,},
        {value: null, figure: 3,}
    ],
    [
        {value: null, figure: 4,},
        {value: null, figure: 4,},
        {value: null, figure: 4,},
        {value: null, figure: 1,},
        {value: null, figure: 1,},
        {value: null, figure: 5,},
        {value: null, figure: 2,},
        {value: null, figure: 2,},
        {value: null, figure: 3,}],
    [
        {value: null, figure: 4,},
        {value: null, figure: 6,},
        {value: null, figure: 4,},
        {value: null, figure: 1,},
        {value: null, figure: 5,},
        {value: null, figure: 5,},
        {value: null, figure: 3,},
        {value: null, figure: 3,},
        {value: null, figure: 3,}],
    [
        {value: null, figure: 4,},
        {value: null, figure: 6,},
        {value: null, figure: 4,},
        {value: null, figure: 5,},
        {value: null, figure: 5,},
        {value: null, figure: 5,},
        {value: null, figure: 7,},
        {value: null, figure: 3,},
        {value: null, figure: 7,}],
    [
        {value: null, figure: 6,},
        {value: null, figure: 6,},
        {value: null, figure: 6,},
        {value: null, figure: 5,},
        {value: null, figure: 5,},
        {value: null, figure: 8,},
        {value: null, figure: 7,},
        {value: null, figure: 3,},
        {value: null, figure: 7,}],
    [
        {value: null, figure: 6,},
        {value: null, figure: 9,},
        {value: null, figure: 9,},
        {value: null, figure: 5,},
        {value: null, figure: 8,},
        {value: null, figure: 8,},
        {value: null, figure: 7,},
        {value: null, figure: 7,},
        {value: null, figure: 7,}],
    [
        {value: null, figure: 6,},
        {value: null, figure: 9,},
        {value: null, figure: 9,},
        {value: null, figure: 9,},
        {value: null, figure: 9,},
        {value: null, figure: 8,},
        {value: null, figure: 7,},
        {value: null, figure: 8,},
        {value: null, figure: 7,}
    ],
    [
        {value: null, figure: 6,},
        {value: null, figure: 6,},
        {value: null, figure: 9,},
        {value: null, figure: 9,},
        {value: null, figure: 9,},
        {value: null, figure: 8,},
        {value: null, figure: 8,},
        {value: null, figure: 8,},
        {value: null, figure: 8,},
    ]
]

arrayTemplates[4] = [[
    {value: null, figure: 1,},
    {value: null, figure: 1,},
    {value: null, figure: 1,},
    {value: null, figure: 2,},
    {value: null, figure: 2,},
    {value: null, figure: 2,},
    {value: null, figure: 3,},
    {value: null, figure: 3,},
    {value: null, figure: 3,}
],
    [
        {value: null, figure: 1,},
        {value: null, figure: 1,},
        {value: null, figure: 2,},
        {value: null, figure: 2,},
        {value: null, figure: 4,},
        {value: null, figure: 2,},
        {value: null, figure: 2,},
        {value: null, figure: 3,},
        {value: null, figure: 3,}
    ],
    [
        {value: null, figure: 5,},
        {value: null, figure: 1,},
        {value: null, figure: 4,},
        {value: null, figure: 2,},
        {value: null, figure: 4,},
        {value: null, figure: 2,},
        {value: null, figure: 4,},
        {value: null, figure: 3,},
        {value: null, figure: 6,}],
    [
        {value: null, figure: 5,},
        {value: null, figure: 1,},
        {value: null, figure: 4,},
        {value: null, figure: 4,},
        {value: null, figure: 4,},
        {value: null, figure: 4,},
        {value: null, figure: 4,},
        {value: null, figure: 3,},
        {value: null, figure: 6,}],
    [
        {value: null, figure: 5,},
        {value: null, figure: 1,},
        {value: null, figure: 1,},
        {value: null, figure: 5,},
        {value: null, figure: 7,},
        {value: null, figure: 6,},
        {value: null, figure: 3,},
        {value: null, figure: 3,},
        {value: null, figure: 6,}],
    [
        {value: null, figure: 5,},
        {value: null, figure: 5,},
        {value: null, figure: 5,},
        {value: null, figure: 5,},
        {value: null, figure: 7,},
        {value: null, figure: 6,},
        {value: null, figure: 6,},
        {value: null, figure: 6,},
        {value: null, figure: 6,}],
    [
        {value: null, figure: 8,},
        {value: null, figure: 8,},
        {value: null, figure: 8,},
        {value: null, figure: 5,},
        {value: null, figure: 7,},
        {value: null, figure: 6,},
        {value: null, figure: 9,},
        {value: null, figure: 9,},
        {value: null, figure: 9,}],
    [
        {value: null, figure: 8,},
        {value: null, figure: 8,},
        {value: null, figure: 8,},
        {value: null, figure: 7,},
        {value: null, figure: 7,},
        {value: null, figure: 7,},
        {value: null, figure: 9,},
        {value: null, figure: 9,},
        {value: null, figure: 9,}
    ],
    [
        {value: null, figure: 8,},
        {value: null, figure: 8,},
        {value: null, figure: 8,},
        {value: null, figure: 7,},
        {value: null, figure: 7,},
        {value: null, figure: 7,},
        {value: null, figure: 9,},
        {value: null, figure: 9,},
        {value: null, figure: 9,},
    ]
]

arrayTemplates[5] = [[
    {value: null, figure: 1,},
    {value: null, figure: 1,},
    {value: null, figure: 1,},
    {value: null, figure: 1,},
    {value: null, figure: 1,},
    {value: null, figure: 2,},
    {value: null, figure: 2,},
    {value: null, figure: 2,},
    {value: null, figure: 2,}
],
    [
        {value: null, figure: 1,},
        {value: null, figure: 1,},
        {value: null, figure: 1,},
        {value: null, figure: 3,},
        {value: null, figure: 1,},
        {value: null, figure: 3,},
        {value: null, figure: 3,},
        {value: null, figure: 3,},
        {value: null, figure: 2,}
    ],
    [
        {value: null, figure: 4,},
        {value: null, figure: 4,},
        {value: null, figure: 3,},
        {value: null, figure: 3,},
        {value: null, figure: 3,},
        {value: null, figure: 3,},
        {value: null, figure: 5,},
        {value: null, figure: 2,},
        {value: null, figure: 2,}],
    [
        {value: null, figure: 4,},
        {value: null, figure: 4,},
        {value: null, figure: 6,},
        {value: null, figure: 3,},
        {value: null, figure: 6,},
        {value: null, figure: 5,},
        {value: null, figure: 5,},
        {value: null, figure: 2,},
        {value: null, figure: 2,}],
    [
        {value: null, figure: 4,},
        {value: null, figure: 6,},
        {value: null, figure: 6,},
        {value: null, figure: 6,},
        {value: null, figure: 6,},
        {value: null, figure: 6,},
        {value: null, figure: 5,},
        {value: null, figure: 5,},
        {value: null, figure: 5,}],
    [
        {value: null, figure: 4,},
        {value: null, figure: 4,},
        {value: null, figure: 6,},
        {value: null, figure: 7,},
        {value: null, figure: 6,},
        {value: null, figure: 5,},
        {value: null, figure: 5,},
        {value: null, figure: 8,},
        {value: null, figure: 8,}],
    [
        {value: null, figure: 4,},
        {value: null, figure: 4,},
        {value: null, figure: 7,},
        {value: null, figure: 7,},
        {value: null, figure: 7,},
        {value: null, figure: 7,},
        {value: null, figure: 5,},
        {value: null, figure: 8,},
        {value: null, figure: 8,}],
    [
        {value: null, figure: 9,},
        {value: null, figure: 9,},
        {value: null, figure: 9,},
        {value: null, figure: 7,},
        {value: null, figure: 9,},
        {value: null, figure: 7,},
        {value: null, figure: 7,},
        {value: null, figure: 7,},
        {value: null, figure: 8,}
    ],
    [
        {value: null, figure: 9,},
        {value: null, figure: 9,},
        {value: null, figure: 9,},
        {value: null, figure: 9,},
        {value: null, figure: 9,},
        {value: null, figure: 8,},
        {value: null, figure: 8,},
        {value: null, figure: 8,},
        {value: null, figure: 8,},
    ]
]

arrayTemplates[6] = [[
    {value: null, figure: 1,},
    {value: null, figure: 1,},
    {value: null, figure: 1,},
    {value: null, figure: 1,},
    {value: null, figure: 2,},
    {value: null, figure: 3,},
    {value: null, figure: 3,},
    {value: null, figure: 3,},
    {value: null, figure: 3,}
],
    [
        {value: null, figure: 1,},
        {value: null, figure: 1,},
        {value: null, figure: 1,},
        {value: null, figure: 2,},
        {value: null, figure: 2,},
        {value: null, figure: 3,},
        {value: null, figure: 2,},
        {value: null, figure: 2,},
        {value: null, figure: 3,}
    ],
    [
        {value: null, figure: 4,},
        {value: null, figure: 4,},
        {value: null, figure: 1,},
        {value: null, figure: 5,},
        {value: null, figure: 2,},
        {value: null, figure: 2,},
        {value: null, figure: 2,},
        {value: null, figure: 2,},
        {value: null, figure: 3,}],
    [
        {value: null, figure: 4,},
        {value: null, figure: 4,},
        {value: null, figure: 1,},
        {value: null, figure: 5,},
        {value: null, figure: 5,},
        {value: null, figure: 6,},
        {value: null, figure: 6,},
        {value: null, figure: 3,},
        {value: null, figure: 3,}],
    [
        {value: null, figure: 4,},
        {value: null, figure: 5,},
        {value: null, figure: 5,},
        {value: null, figure: 5,},
        {value: null, figure: 6,},
        {value: null, figure: 6,},
        {value: null, figure: 6,},
        {value: null, figure: 6,},
        {value: null, figure: 6,}],
    [
        {value: null, figure: 4,},
        {value: null, figure: 4,},
        {value: null, figure: 7,},
        {value: null, figure: 5,},
        {value: null, figure: 5,},
        {value: null, figure: 6,},
        {value: null, figure: 6,},
        {value: null, figure: 8,},
        {value: null, figure: 8,}],
    [
        {value: null, figure: 4,},
        {value: null, figure: 4,},
        {value: null, figure: 7,},
        {value: null, figure: 5,},
        {value: null, figure: 9,},
        {value: null, figure: 9,},
        {value: null, figure: 9,},
        {value: null, figure: 9,},
        {value: null, figure: 8,}],
    [
        {value: null, figure: 7,},
        {value: null, figure: 7,},
        {value: null, figure: 7,},
        {value: null, figure: 9,},
        {value: null, figure: 9,},
        {value: null, figure: 8,},
        {value: null, figure: 9,},
        {value: null, figure: 9,},
        {value: null, figure: 8,}
    ],
    [
        {value: null, figure: 7,},
        {value: null, figure: 7,},
        {value: null, figure: 7,},
        {value: null, figure: 7,},
        {value: null, figure: 9,},
        {value: null, figure: 8,},
        {value: null, figure: 8,},
        {value: null, figure: 8,},
        {value: null, figure: 8,},
    ]
]